@startuml

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam participant {
BackgroundColor AWS_BG_COLOR
BorderColor AWS_BORDER_COLOR
}

skinparam sequence {
LifeLineBorderColor DodgerBlue
LifeLineBackgroundColor APPLICATION

ActorBackgroundColor APPLICATION
ActorBorderColor DodgerBlue

BackgroundColor #FFFFFF
ArrowColor DodgerBlue
BorderColor DodgerBlue
ParticipantBorderColor DodgerBlue

GroupBorderColor #082642
GroupBackgroundColor APPLICATION
}

'-Title----------------------------------------------------------------------------------------------------------------

title US 07 - Use Shopping Cart

'-Actors/Participants--------------------------------------------------------------------------------------------------

actor "<b>Client" as A
participant "<b>WeaponsPage" as WR
participant "<b>ShoppingCartService" as SC
participant "<b>BackEnd" as BE

'-Associations---------------------------------------------------------------------------------------------------------

activate A

A -> WR: Selects a Weapon to add to the Shopping Cart
activate WR

WR -> SC: addToCart(weapon)
activate SC

SC -> BE: HTTP request (POST)
activate BE
BE --> SC : confirmation of addition
deactivate BE

SC --> WR : confirmation of addition
deactivate SC
WR -> A: Displays the updated Shopping Cart
deactivate WR

A -> WR: Removes a Weapon from the Shopping Cart
activate WR

WR -> SC: removeFromCart(weapon)
activate SC

SC -> BE: HTTP request (DELETE)
activate BE
BE --> SC : confirmation of removal
deactivate BE

SC --> WR : confirmation of removal
deactivate SC
WR -> A: Displays the updated Shopping Cart
deactivate WR

'----------------------------------------------------------------------------------------------------------------------

@enduml