@startuml

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam participant {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}

skinparam sequence {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}


'-Title----------------------------------------------------------------------------------------------------------------

title US 05 - View of Weapons with Filters

'-Actors/Participants--------------------------------------------------------------------------------------------------

actor "<b>Client" as A
participant "<b>System" as CR


'-Associations---------------------------------------------------------------------------------------------------------

activate A

A -> CR: AAsks to see Weapons with filters
activate CR


CR -> A: Shows Weapons with filters and informs the user of the operation's success
deactivate CR
'----------------------------------------------------------------------------------------------------------------------

@enduml