@startuml

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam participant {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}

skinparam sequence {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}


'-Title----------------------------------------------------------------------------------------------------------------

title US 10 - As a client, I want to edit my profile information such as delivery address and contact details.

'-Actors/Participants--------------------------------------------------------------------------------------------------


actor "<b>Client" as A
participant "<b>DashboardPage" as CR
participant "<b>DashboardService" as CC
participant "<b>BackEnd" as BE



'-Associations---------------------------------------------------------------------------------------------------------

activate A
A -> CR: Asks to update his profile information
activate CR
CR --> A: RequestInformation(name,password,birthDate,phoneNumber,address)

A -> CR: Fills in the updated information

CR -> CC: updateUser(name,email,password,birthDate,phoneNumber,address)

activate CC
CC -> CC : verifyFormat(name,password,birthDate,phoneNumber,address)
activate CC
deactivate CC

CC -> BE: HTTP request (PUT)
activate BE
BE --> CC : updatedClient
deactivate BE



CC-->CR : updatedClient
deactivate CC
CR -> A: Shows the users updated information and informs the user of the operation's success
deactivate CR
'----------------------------------------------------------------------------------------------------------------------

@enduml