@startuml

'-Style----------------------------------------------------------------------------------------------------------------

autonumber

skinparam DefaultTextAlignment center

skinparam BackgroundColor #fafdff

skinparam participant {
    BackgroundColor AWS_BG_COLOR
    BorderColor AWS_BORDER_COLOR
}

skinparam sequence {
    LifeLineBorderColor DodgerBlue
    LifeLineBackgroundColor APPLICATION

    ActorBackgroundColor APPLICATION
    ActorBorderColor DodgerBlue

    BackgroundColor #FFFFFF
    ArrowColor DodgerBlue
    BorderColor DodgerBlue
    ParticipantBorderColor DodgerBlue

    GroupBorderColor #082642
    GroupBackgroundColor APPLICATION
}


'-Title----------------------------------------------------------------------------------------------------------------

title US 02 - Apply to a license

'-Actors/Participants--------------------------------------------------------------------------------------------------

actor "<b>Client" as A
participant "<b>System" as CR


'-Associations---------------------------------------------------------------------------------------------------------

activate A

A -> CR: Asks to apply to a license
activate CR


CR -> A: Requests the documentation and data

A -> CR: Insert the documents and data
CR -> A: Informs the success/failure of the application

deactivate CR
'----------------------------------------------------------------------------------------------------------------------

@enduml