@startuml
'https://plantuml.com/class-diagram
hide methods
skinparam classAttributeIconSize 0




package Users{
class Client{
-clientID
-name
-email
-password
-birthDate
-phoneNumber
-address
}

}

@enduml